# Generated by Django 5.1.4 on 2025-01-15 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['created_at'], 'verbose_name': 'Ox', 'verbose_name_plural': 'Oxen'},
        ),
    ]
